apiVersion: v1
kind: Service
metadata:
  namespace: demo3
  labels:
    app: svc-client
  name: svc-client
spec:
  ports:
  - name: http-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: client-demo3
